// <auto-generated />
using System;
using AttendanceApp.WebApi.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AttendanceApp.WebApi.Migrations
{
    [DbContext(typeof(AttendanceContext))]
    [Migration("20231123170516_inital2")]
    partial class inital2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.14");

            modelBuilder.Entity("AttendanceApp.WebApi.Entities.Attendance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("AttendanceDay")
                        .HasColumnType("TEXT");

                    b.Property<bool>("ClockedIn")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ClockedInAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("ClockedOut")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ClockedOutAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AttenanceRecords");
                });

            modelBuilder.Entity("AttendanceApp.WebApi.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswrodHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserName")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("74dc724f-56b6-47c2-859b-10fc36fbdeb5"),
                            FullName = "User 1 Full Name",
                            PasswrodHash = "user 1 password hashed",
                            Role = "employee",
                            UserName = "UserName1"
                        },
                        new
                        {
                            Id = new Guid("c66ee6e9-bbca-480b-9bc6-2d52f680b9b5"),
                            FullName = "User 2 Full Name",
                            PasswrodHash = "user 2 password hashed",
                            Role = "employee",
                            UserName = "UserName2"
                        },
                        new
                        {
                            Id = new Guid("a03783cb-d63c-4c85-8dbd-c29e31566a7b"),
                            FullName = "User 3 Full Name",
                            PasswrodHash = "user 3 password hashed",
                            Role = "employee",
                            UserName = "UserName3"
                        });
                });

            modelBuilder.Entity("AttendanceApp.WebApi.Entities.Attendance", b =>
                {
                    b.HasOne("AttendanceApp.WebApi.Entities.User", "User")
                        .WithMany("AttendanceRecords")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("AttendanceApp.WebApi.Entities.User", b =>
                {
                    b.Navigation("AttendanceRecords");
                });
#pragma warning restore 612, 618
        }
    }
}
